Project3Unity/Controllers/BugController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project3Unity.Controllers
{
    [Authorize(Roles = "Administrator,User")]
    public class BugController : Controller
    {
        private project3Entities db = new project3Entities();

        //
        // GET: /Bug/
        [AllowAnonymous]
        public ActionResult Index(int? page, string searchString)
        {
            int pageNumber = page ?? 1;
            ViewBag.Leaderboard = Utilities.GetTopScores(10);

            // If user is authenticated, pass to ViewBag all roleNames associated with the user
            // The list is used to deny normal users from editing and deleting bug reports
            if (User.Identity.IsAuthenticated)
            {
                List<string> userRoles = new List<string>();
                var airs = db.AccountsInRoles.Where(m => m.accEmail.Equals(User.Identity.Name)).ToList();
                foreach (AccountsInRole item in airs)
                {
                    userRoles.Add(item.Role.roleName);
                }
                ViewBag.UserRoles = userRoles;
            }

            var bugs = (from b in db.Bugs
                        orderby b.bugID descending
                        select b).Include(b => b.Account);

            // Filter the data through the search string
            if (!String.IsNullOrWhiteSpace(searchString))
            {
                bugs = bugs.Where(b =>
                    b.Account.accUsername.ToUpper().Contains(searchString.ToUpper()) ||
                    b.bugTitle.ToUpper().Contains(searchString.ToUpper()));
            }
            
            return View(bugs.ToPagedList(pageNumber, 10));
        }

        //
        // GET: /Bug/Details/5
        [AllowAnonymous]
        public ActionResult Details(int id = 0)
        {
            Bug bug = db.Bugs.Find(id);
            if (bug == null)
            {
                return HttpNotFound();
            }

            // Preview file
            if (bug.bugFile != null)
            {
                string directory = HttpRuntime.AppDomainAppPath + "Upload/Bug";
                //string testurl = Path.Combine(new string[] { HttpRuntime.AppDomainAppPath, "Upload", "Bug", bug.bugFile });
                string fileUrl = Path.Combine(directory, bug.bugFile);
                FileInfo file = new FileInfo(fileUrl);
                string ext = file.Extension;

                //Determine if the file associated is an image or a video
                bool isImage = false, isVideo = false;
                string[] imageExts = { ".jpg", ".jpeg", ".png", ".gif" };
                foreach (string item in imageExts)
                {
                    if (ext.Equals(item))
                    {
                        isImage = true;
                        break;
                    }
                }
                if (!isImage)
                {
                    if (ext.Equals(".mp4"))
                    {
                        isVideo = true;
                    }
                }

                ViewBag.IsImage = isImage;
                ViewBag.IsVideo = isVideo;
                ViewBag.FileExtension = ext;
                ViewBag.FileUrl = "/Upload/Bug/" + bug.bugFile;
            }

            ViewBag.Leaderboard = Utilities.GetTopScores(10);
            return View(bug);
        }

        //
        // GET: /Bug/Create
        public ActionResult Create()
        {
            ViewBag.LeaderBoard = Utilities.GetTopScores(10);

            return View();
        }

        //
        // POST: /Bug/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Bug bug, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                // Add file to the filesystem
                string bugFile = null;
                if (file != null)
                {
                    if (file.ContentLength > 262144000)
                    {
                        ModelState.AddModelError("", "File size is too large, must be at most 250MB");
                        return View(bug);
                    }
                    string fileExt = Path.GetExtension(file.FileName);
                    Guid newFileName = Guid.NewGuid();
                    bugFile = newFileName + fileExt;

                    // Upload the file to the base directory
                    string directory = HttpRuntime.AppDomainAppPath + "Upload/Bug";
                    //string directory = AppDomain.CurrentDomain.BaseDirectory + "Upload/Bug";
                    file.SaveAs(Path.Combine(directory, bugFile));
                }

                bug.bugFile = bugFile;
                db.Bugs.Add(bug);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.LeaderBoard = Utilities.GetTopScores(10);
            ModelState.AddModelError("", "Invalid form submission");
            return View(bug);
        }

        //
        // GET: /Bug/Edit/5
        [Authorize(Roles = "Administrator")]
        public ActionResult Edit(int id = 0)
        {
            Bug bug = db.Bugs.Find(id);
            if (bug == null)
            {
                return HttpNotFound();
            }

            ViewBag.LeaderBoard = Utilities.GetTopScores(10);
            return View(bug);
        }

        //
        // POST: /Bug/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public ActionResult Edit(string oldFile, Bug bug, HttpPostedFileBase newFile)
        {
            if (ModelState.IsValid)
            {
                // Add file to the filesystem and delete old file
                string bugFile = null;
                if (newFile != null)
                {
                    if (newFile.ContentLength > 262144000)
                    {
                        ModelState.AddModelError("", "File size is too large, must be at most 250MB");
                        ViewBag.LeaderBoard = Utilities.GetTopScores(10);
                        return View(bug);
                    }
                    string fileExt = Path.GetExtension(newFile.FileName);
                    Guid newFileName = Guid.NewGuid();
                    bugFile = newFileName + fileExt;

                    // Upload the file to the base directory
                    string directory = HttpRuntime.AppDomainAppPath + "Upload/Bug";
                    newFile.SaveAs(Path.Combine(directory, bugFile));

                    // Delete old file
                    if (!oldFile.Equals(""))
                    {
                        string oldPath = Server.MapPath("~/Upload/Bug/" + oldFile);
                        FileInfo old = new FileInfo(oldPath);
                        if (old.Exists)
                        {
                            old.Delete();
                        }
                    }
                }

                bug.bugFile = bugFile;
                db.Bugs.Attach(bug);
                var entry = db.Entry(bug);
                entry.Property(e => e.bugTitle).IsModified = true;
                entry.Property(e => e.bugDesc).IsModified = true;
                entry.Property(e => e.bugFile).IsModified = true;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.LeaderBoard = Utilities.GetTopScores(10);
            ModelState.AddModelError("", "Invalid form submission");
            return View(bug);
        }

        //
        // GET: /Bug/Delete/5
        [Authorize(Roles = "Administrator")]
        public ActionResult Delete(int id = 0)
        {
            Bug bug = db.Bugs.Find(id);
            if (bug == null)
            {
                return HttpNotFound();
            }

            // Preview file
            if (bug.bugFile != null)
            {
                string directory = HttpRuntime.AppDomainAppPath + "Upload/Bug";
                string fileUrl = Path.Combine(directory, bug.bugFile);
                FileInfo file = new FileInfo(fileUrl);
                string ext = file.Extension;

                //Determine if the file associated is an image or a video
                bool isImage = false, isVideo = false;
                string[] imageExts = { ".jpg", ".jpeg", ".png", ".gif" };
                foreach (string item in imageExts)
                {
                    if (ext.Equals(item))
                    {
                        isImage = true;
                        break;
                    }
                }
                if (!isImage)
                {
                    if (ext.Equals(".mp4"))
                    {
                        isVideo = true;
                    }
                }

                ViewBag.IsImage = isImage;
                ViewBag.IsVideo = isVideo;
                ViewBag.FileExtension = ext;
                ViewBag.FileUrl = "/Upload/Bug/" + bug.bugFile;
            }

            ViewBag.LeaderBoard = Utilities.GetTopScores(10);
            return View(bug);
        }

        //
        // POST: /Bug/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public ActionResult DeleteConfirmed(int id)
        {
            Bug bug = db.Bugs.Find(id);
            db.Bugs.Remove(bug);
            db.SaveChanges();

            // Delete file associated with the deleted bug report
            if (bug.bugFile != null)
            {
                string path = Server.MapPath("~/Upload/Bug/" + bug.bugFile);
                FileInfo file = new FileInfo(path);
                if (file.Exists)
                {
                    file.Delete();
                }
            }

Project3Unity/Controllers/HighScoreController.cs
using PagedList;
using Project3Unity.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;

namespace Project3Unity.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class HighScoreController : Controller
    {
        private project3Entities db = new project3Entities();

        //
        // GET: /HighScore/
        [AllowAnonymous]
        public ActionResult Index(int? page, string searchString)
        {
            List<ScoreRank> rankedScores = new List<ScoreRank>();
            int pageNumber = page ?? 1;

            var highScores = (from s in db.HighScores
                              orderby s.srcHS descending
                              select s).Include(h => h.Account);

            // Rank the scores
            int rank = 1;
            foreach (HighScore item in highScores)
            {
                rankedScores.Add(new ScoreRank() { Rank = rank, Score = item });
                rank++;
            }

            // Filter the data through the search string
            if (!String.IsNullOrWhiteSpace(searchString))
            {
                IEnumerable<ScoreRank> filteredRankedScores = new List<ScoreRank>();
                int searchNumber;
                if (int.TryParse(searchString, out searchNumber))
                {
                    filteredRankedScores = rankedScores.Where(rs =>
                        rs.Rank == searchNumber ||
                        rs.Score.Account.accUsername.ToUpper().Contains(searchString.ToUpper()));
                }
                else
                {
                    filteredRankedScores = rankedScores.Where(rs =>
                        rs.Score.Account.accUsername.ToUpper().Contains(searchString.ToUpper()));
                }
                return View(filteredRankedScores.ToPagedList(pageNumber, 10));
            }
            
            return View(rankedScores.ToPagedList(pageNumber, 10));
        }

        //
        // GET: /HighScore/Create
        [AllowAnonymous]
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /HighScore/Create

        [ValidateAntiForgeryToken]
        [AllowAnonymous]
        public ActionResult Create(HighScore highscore)
        {
            if (ModelState.IsValid)
            {
                db.HighScores.Add(highscore);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(highscore);
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Project3Unity/Views/Shared/_Footer.cshtml
<footer class="footer" style="margin-bottom: 0">
    <div class="container-fluid">
        <div class="pull-left">
            <a href="http://daihoc.fpt.edu.vn/" target="_blank">
                <img width="118" height="36" src="~/Images/fpt.png">
            </a>
            <p>&copy; @DateTime.Now.Year - FU Games</p>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul id="menu" class="nav navbar-nav">
                <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                <li>@Html.ActionLink("About", "About", "Home")</li>
            </ul>
        </div>
    </div>
</footer>

Project3Unity/Views/Shared/_Header.cshtml
<header>
    <div class="topnav" id="wrapper" style="margin-bottom: 0" role="navigation">
        <div class="navbar-header">
            <button class="navbar-toggle collapsed" aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" type="button">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @*<p class="site-title">@Html.ActionLink("your logo here", "Index", "Home")</p>*@
            <a class="site-title" href="/"><img src="/Images/index.png" alt="Logo" height="55" width="130" /></a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <div id="login" class="pull-right" style="background-color: #f5f5f5">
                @Html.Partial("_LoginPartial")
            </div>

            <ul id="menu" class="nav navbar-nav">
                <li>@Html.ActionLink("Download Game", "Game", "Home")</li>
                <li>@Html.ActionLink("Leaderboard", "Index", "HighScore")</li>
                <li>@Html.ActionLink("Suggestion", "Index", "Suggestion")</li>
                <li>@Html.ActionLink("Report Bug", "Index", "Bug")</li>
                <li>@Html.ActionLink("Review", "Index", "Review")</li>
                <li>@Html.ActionLink("Help", "Help", "Home")</li>
            </ul>
        </div>
    </div>
</header>

Project3Unity/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - FU Games</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />

        <link href="/Content/Css/StyleSheet1.css" rel="stylesheet" />
        <!-- Bootstrap Core CSS -->
        <link href="/Content/Bootstrap/bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
        <!-- MetisMenu CSS -->
        <link href="/Content/Bootstrap/bower_components/metisMenu/dist/metisMenu.min.css" rel="stylesheet">
        <!-- Custom CSS -->
        <link href="/Content/Bootstrap/dist/css/sb-admin-2.css" rel="stylesheet">
        <!-- Custom Fonts -->
        <link href="/Content/Bootstrap/bower_components/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
        @*@Styles.Render("~/Content/css")*@
        @RenderSection("AddCSS", required: false)
        @Scripts.Render("~/bundles/modernizr")
        @RenderSection("AddJS", required: false)
    </head>
    <body>
        @Html.Partial("_Header")
        @RenderSection("Sidebar", required: false)
        <div id="body" class="container">
            <div class="row">
                @RenderSection("featured", required: false)
                <section class="content-wrapper main-content clear-fix">
                    @RenderBody()
                </section>
            </div>
        </div>
        @RenderSection("Footer", required: false)
        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)

        <!-- jQuery -->
        <script src="/Content/Bootstrap/bower_components/jquery/dist/jquery.min.js"></script>
        <!-- Bootstrap Core JavaScript -->
        <script src="/Content/Bootstrap/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
        <!-- Metis Menu Plugin JavaScript -->
        <script src="/Content/Bootstrap/bower_components/metisMenu/dist/metisMenu.min.js"></script>
        <!-- Custom Theme JavaScript -->
        <script src="/Content/Bootstrap/dist/js/sb-admin-2.js"></script>
    </body>
</html>

Project3Unity/Views/Shared/_Sidebar.cshtml
@*<aside class="float-left">*@
    @if (ViewBag.LeaderBoard != null)
{
    <div class="wrapper">
        <div class="container-table col-md-2" style="padding-top:7%;position:static">
            <table class="table table-bordered m-n" cellspacing="0">
                <thead>
                    <tr style="background-color: gray;">
                        <th>#</th>
                        <th>Username</th>
                        <th>Score</th>
                    </tr>
                </thead>
                <tbody>
                    @{
    int n = 1;
                    }
                    @foreach (var item in ViewBag.LeaderBoard)
                    {
                        <tr>
                            <td>@n</td>
                            <td>@item.Account.accUsername</td>
                            <td>@item.srcHS</td>
                        </tr>
                        n++;
                    }
                </tbody>

            </table>
        </div>
    </div>
}
else
{
    //
}
@*</aside>*@